export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ADD_ORDER = "ADD_ORDER";
export const REMOVE_ORDER = "REMOVE_ORDER";
export const CART_PRODUCTS = "CART_PRODUCTS";
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS";
export const INCREASE_ITEM = "INCREASE_ITEM";
export const DECREASE_ITEM = "DECREASE_ITEM";